### ISSUE TITLE
EU Endpoint verification URL is wrong

### ISSUE THREAD

**Issue by benedikt-dreier** [nitsan-technologies/ns_friendlycaptcha#9]
Dear Team NITSAN,

I think the verification URL for the EU endpoint is wrong. Should be
`$verifyServerInfo = 'https://eu-api.friendlycaptcha.eu/api/v1/siteverify';`

but is:
`$verifyServerInfo = 'https://eu-api.friendlycaptcha.eu/api/v1/puzzle';`

Best regards

_Originally posted by @benedikt-dreier in https://github.com/nitsan-technologies/ns_friendlycaptcha/issues/7#issuecomment-1578428670_

**Comment by benedikt-dreier** [comment]
Hey,

thanks a lot, but I think you misunderstood the endpoints:

**/puzzle** is always for the frontend, source: https://docs.friendlycaptcha.com/#/widget_api?id=data-puzzle-endpoint
`Resources/Private/Frontend/Partials/Recaptcha.html`

**/siteverify** is always the backend verification, source: https://docs.friendlycaptcha.com/#/verification_api
`Classes/Services/CaptchaService.php`

I think there is no need for the additional constant. Please correct me if I am wrong.

Best regards

**Comment by nitsan-technologies** [comment]
Hey @benedikt-dreier 
Sorry for the late reply.

The option is required in case when the user wants EU-Endpoint enable as well he wants to use PUZZLE then the following API call will fire.

![image](https://github.com/nitsan-technologies/ns_friendlycaptcha/assets/2622317/d645fb73-a046-49a6-b745-ada6eb4c88d5)
API call: https://eu-api.friendlycaptcha.eu/api/v1/puzzle?sitekey

In only EU-Endpoint enable it will call : 
![image](https://github.com/nitsan-technologies/ns_friendlycaptcha/assets/2622317/95279bdd-2ce7-460b-ba82-13fbd34af21a)
API call: https://eu-api.friendlycaptcha.eu/api/v1/siteverify?sitekey=

That's why we are keeping both options.
Thanks!

Cheers, Team NITSAN
